server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://hiima-it.ck0u7o3jzfwy.ap-northeast-1.rds.amazonaws.com/hiima
    username: root
    password: eternalhiima
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      use-new-id-generator-mappings: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
