server:
  port: 8090

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://hiima-it.ck0u7o3jzfwy.ap-northeast-1.rds.amazonaws.com/hiima
    username: root
    password: eternalhiima
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      use-new-id-generator-mappings: false
